services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $tempDir: '%kernel.project_dir%/var'

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Behavior,DataFixtures,DQL,Entity,Repository,Resources}'
