cards_list:
    path:  /{_locale}/set/{pack_code}/{view}/{sort}/{page}
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:list
        _locale: en
        view: list
        sort: set
        page: 1
    requirements:
        _locale: \w\w

cards_zoom:
    path:  /{_locale}/card/{card_code}
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:zoom
        _locale: en
    requirements:
        _locale: \w\w
        card_code: \d+

cards_cycle:
    path:  /{_locale}/cycle/{cycle_code}/{view}/{sort}/{page}
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:cycle
        _locale: en
        view: list
        sort: faction
        page: 1
    requirements:
        _locale: \w\w

cards_search:
    path:  /{_locale}/search
    defaults:
        _controller: NetrunnerdbCardsBundle:Default:search
        _locale: en
    requirements:
        _locale: \w\w

cards_find:
    path:  /find/
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:find

cards_processSearchForm:
    path:  /process/
    defaults:
        _controller: NetrunnerdbCardsBundle:Search:process

cards_about:
    path:  /{_locale}/about
    defaults:
        _controller: NetrunnerdbCardsBundle:Default:about
        _locale: en
    requirements:
        _locale: \w\w

cards_api:
    path:  /{_locale}/apidoc
    defaults:
        _controller: NetrunnerdbCardsBundle:Default:apidoc
        _locale: en
    requirements:
        _locale: \w\w

cards_rulings:
    path:  /{_locale}/rules
    defaults:
        _controller: NetrunnerdbCardsBundle:Default:rules
        _locale: en
    requirements:
        _locale: \w\w

api_cards:
    path: /api/cards/
    defaults:
        _controller: NetrunnerdbCardsBundle:Api:cards

api_card:
    path: /api/card/{card_code}.{_format}
    defaults:
        _controller: NetrunnerdbCardsBundle:Api:card
        _format: json
    requirements:
        _format: json
        card_code: \d+

api_sets:
    path: /api/sets/
    defaults:
        _controller: NetrunnerdbCardsBundle:Api:sets

api_set:
    path: /api/set/{pack_code}.{_format}
    defaults:
        _controller: NetrunnerdbCardsBundle:Api:set
        _format: json
    requirements:
        _format: json|xml|xlsx|xls

translation_index:
    path: /translation
    defaults:
        _controller: NetrunnerdbCardsBundle:Translation:index

translation_overview:
    path: /translation/{localeCode}
    defaults:
        _controller: NetrunnerdbCardsBundle:Translation:overview

translation_entity_index:
    path: /translation/{localeCode}/{entityName}/index
    defaults:
        _controller: NetrunnerdbCardsBundle:Translation:entityIndex

translation_entity_form:
    path: /translation/{localeCode}/{entityName}/{recordId}/translate
    defaults:
        _controller: NetrunnerdbCardsBundle:Translation:entityForm
        