Netrunnerdb\CardsBundle\Entity\Side:
    type: entity
    table: side
    repositoryClass: Netrunnerdb\CardsBundle\Repository\SideRepository
    gedmo:
        translation:
            locale: locale
    indexes:
        name_index:
            columns: [ name ]
    oneToMany:
        cards:
            targetEntity: Card
            mappedBy: side
        factions:
            targetEntity: Faction
            mappedBy: side
        decks:
            targetEntity: Netrunnerdb\BuilderBundle\Entity\Deck
            mappedBy: side
        decklists:
            targetEntity: Netrunnerdb\BuilderBundle\Entity\Decklist
            mappedBy: side
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            unique: true
            length: 10
        name:
            type: string
            length: 255
            gedmo:
                - translatable
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
