parameters:
    judge.class: AppBundle\Service\Judge
    decks.class: AppBundle\Service\Decks
    decklists.class: AppBundle\Service\Decklists
    reviews.class: AppBundle\Service\Reviews
    texts.class: AppBundle\Service\Texts
    diff.class: AppBundle\Service\Diff

services:
    cards_data:
        class: 'AppBundle\Service\CardsData'
        arguments: ["@doctrine", "@request_stack", "@router"]
    judge:
        class: "%judge.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    decks:
        class: "%decks.class%"
        arguments: ["@doctrine.orm.entity_manager", "@judge", "@diff", "@logger"]
    decklists:
        class: "%decklists.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    reviews:
        class: "%reviews.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    texts:
        class: "%texts.class%"
        arguments: ["%kernel.root_dir%"]
    diff:
        class: "%diff.class%"
        arguments: ["@doctrine.orm.entity_manager"]
    activity_helper:
        class: AppBundle\Helper\ActivityHelper
        arguments: ["@doctrine"]
    moderation_helper:
        class: AppBundle\Helper\ModerationHelper
        arguments: ["@doctrine"]
    personalization_helper:
        class: AppBundle\Helper\PersonalizationHelper
        arguments: ["@doctrine", "@activity_helper", "@security.authorization_checker"]