AppBundle\Entity\Reviewcomment:
    type: entity
    table: reviewcomment
    repositoryClass: AppBundle\Entity\ReviewcommentRepository
    manyToOne:
        author:
            targetEntity: AppBundle\Entity\User
            nullable: false
            joinColumn:
                name: user_id
                referencedColumnName: id
        review:
            targetEntity: AppBundle\Entity\Review
            nullable: false
            inversedBy: comments
            joinColumn:
                name: review_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        dateCreation:
            type: datetime
            column: date_creation
            gedmo:
                timestampable:
                    on:  create
        dateUpdate:
            type: datetime
            column: date_update
            gedmo:
                timestampable:
                    on:  update
        text:
            type: text
            nullable: false
    lifecycleCallbacks: {  }
